services:
  dash:
    build:
        context: .
        dockerfile: Dockerfile
#    image: mgutierrezc442/dashcontainer
    ports:
      - "8050:8050"
    env_file:
      - .env
    volumes:
      - ./:/contrans2024
    networks:
      - dbnetwork

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes: # local address or name of volume you created : container address 
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    networks:
      - dbnetwork

volumes: # creates volumes
  postgresdata:
  mongodata:

networks:
  dbnetwork:

